language: python

python:
  - "2.7"

sudo: false

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - paver setup

script:
  - echo -e "admin\ntest\ntest\nyou@example.com\nyou@example.com" | python GeoHealthCheck/models.py create
  - find . -name "*.py" | grep -v docs | xargs flake8
  - cd docs && make html
  - python GeoHealthCheck/models.py load tests/data/fixtures.json y
  - python GeoHealthCheck/models.py run
  - python tests/run_tests.py

after-script:
  - python GeoHealthCheck/models.py drop
