language: python

python:
  - "2.7"

sudo: false

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - paver setup

script:
  - echo -e "admin\ntest\ntest\nyou@example.com\nyou@example.com" | python GeoHealthCheck/models.py create
  - find . -name "*.py" | grep -v docs | xargs pep8
  - find . -name "*.py" | grep -v docs | xargs pyflakes
  - cd docs && make html

after-script:
  - python GeoHealthCheck/models.py drop
