language: python

python:
  - "2.7"

sudo: false

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - paver setup

  - echo "[https://www.transifex.com]\n" > ~/.transifexrc
  - echo "hostname = https://www.transifex.com\n" >> ~/.transifexrc
  - echo "username = ${TRANSIFEX_USERNAME}\n" >> ~/.transifexrc
  - echo "password = ${TRANSIFEX_PASSWORD}\n" >> ~/.transifexrc
  - echo "token = \n" >> ~/.transifexrc
  - cat ~/.transifexrc
  - tx pull -a

script:
  - echo -e "admin\ntest\ntest\nyou@example.com\nyou@example.com" | python GeoHealthCheck/models.py create
  - find . -name "*.py" | grep -v docs | xargs pep8
  - find . -name "*.py" | grep -v docs | xargs pyflakes
  - cd docs && make html

after-script:
  - python GeoHealthCheck/models.py drop
