version: "3"

services:
  geohealthcheck:
    image: yjacolin/geohealthcheck:latest
    ports:
      - 8083:80
    volumes:
      - ghc_sqlitedb:/GeoHealthCheck/DB

  geohealthcheck-cron-hourly:
    image: yjacolin/geohealthcheck:latest
    depends_on:
      - geohealthcheck
    entrypoint:
      - bash
      - /cron-jobs-hourly.sh
    volumes:
      - ghc_sqlitedb:/GeoHealthCheck/DB
    labels:
      io.ghc-cron-hourly: 'true'

  geohealthcheck-cron-daily:
    image: yjacolin/geohealthcheck:latest
    depends_on:
      - geohealthcheck
    entrypoint:
      - bash
      - /cron-jobs-daily.sh
    volumes:
      - ghc_sqlitedb:/GeoHealthCheck/DB
    labels:
      io.ghc-cron-daily: 'true'

  jobber:
    image: blacklabelops/jobber:docker.v1.1
    depends_on:
      - geohealthcheck-cron-hourly
      - geohealthcheck-cron-daily
    environment:
      JOB_NAME1: ghc-cron-hourly
      JOB_COMMAND1: docker start $$(docker ps -a -f label=io.ghc-cron-hourly=true --format="{{.ID}}")
      JOB_TIME1: 0 0 *
      JOB_NAME2: ghc-cron-daily
      JOB_COMMAND2: docker start $$(docker ps -a -f label=io.ghc-cron-daily=true --format="{{.ID}}")
      JOB_TIME2: 0 45 0 *
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

# docker-compose v2+ needs separate volumes section
volumes:
  ghc_sqlitedb:
